const fs = require('fs');
const path = require('path');

const rootConfigPath = path.join(__dirname, '../../echo.config.json');
const packageJsonPath = path.join(__dirname, '../../package.json');
const siteConfigTsPath = path.join(__dirname, '../../src/config/site.ts');

function syncConfig() {
  try {
    if (!fs.existsSync(rootConfigPath)) {
      console.error('❌ echo.config.json not found in root!');
      return;
    }

    const configContent = fs.readFileSync(rootConfigPath, 'utf8');
    const config = JSON.parse(configContent);
    
    // 1. Read package.json for version
    const packageJsonContent = fs.readFileSync(packageJsonPath, 'utf8');
    const packageJson = JSON.parse(packageJsonContent);
    const version = packageJson.version;

    // 2. Generate src/config/site.ts
    // We generate this file so the frontend can import it with types
    const siteTsContent = `// This file is auto-generated from echo.config.json and package.json
// Do not edit this file directly. Edit echo.config.json or package.json in the root instead.

export const siteConfig = {
  name: "${config.displayName}",
  description: "${config.description}",
  version: "${version}",
  // Server configuration references
  server: {
    host: process.env.HOST || "${config.server.host}",
    ports: {
      dev: ${config.server.ports.dev},
      prod: ${config.server.ports.prod},
    },
  },
  // Domain configuration
  domain: {
    // Used for production links
    production: "${config.domain.production}", 
    // Used for development links
    development: "${config.domain.development}",
  },
};

export function getBaseUrl() {
  // 1. Prefer explicit env var
  if (process.env.NEXT_PUBLIC_APP_URL) {
    return process.env.NEXT_PUBLIC_APP_URL;
  }
  
  // 2. Check for NextAuth URL (often set in prod)
  if (process.env.NEXTAUTH_URL) {
    return process.env.NEXTAUTH_URL;
  }

  // 3. Development fallback
  if (process.env.NODE_ENV === "development") {
    return \`\${siteConfig.domain.development}:\${siteConfig.server.ports.dev}\`;
  }

  // 4. Production fallback
  return siteConfig.domain.production;
}
`;

    fs.writeFileSync(siteConfigTsPath, siteTsContent);
    console.log('✅ src/config/site.ts generated from echo.config.json');

  } catch (error) {
    console.error('Failed to sync config:', error);
  }
}

module.exports = syncConfig;

if (require.main === module) {
  syncConfig();
}
