// This file is auto-generated from echo.config.json and package.json
// Do not edit this file directly. Edit echo.config.json or package.json in the root instead.

export const siteConfig = {
  name: "Echo",
  description: "A platform for deep listening and precision learning.",
  version: "0.1.0",
  // Server configuration references
  server: {
    host: process.env.HOST || "0.0.0.0",
    ports: {
      dev: 17891,
      prod: 18474,
    },
  },
  // Domain configuration
  domain: {
    // Used for production links
    production: "https://echo.catplot.org", 
    // Used for development links
    development: "http://localhost",
  },
};

export function getBaseUrl() {
  // 1. Prefer explicit env var
  if (process.env.NEXT_PUBLIC_APP_URL) {
    return process.env.NEXT_PUBLIC_APP_URL;
  }
  
  // 2. Check for NextAuth URL (often set in prod)
  if (process.env.NEXTAUTH_URL) {
    return process.env.NEXTAUTH_URL;
  }

  // 3. Development fallback
  if (process.env.NODE_ENV === "development") {
    return `${siteConfig.domain.development}:${siteConfig.server.ports.dev}`;
  }

  // 4. Production fallback
  return siteConfig.domain.production;
}
